# https://github.com/Homebrew/homebrew-bundle

# need device password
cask "1password/tap/1password-cli"
cask "google-cloud-sdk"

# cask "EasyRres" # https://apps.apple.com/jp/app/easyres/id688211836
cask "evernote"
cask "font-fira-code-nerd-font"
cask "font-Hack-nerd-font"
cask "ngrok"
cask "postman"
cask "spotify"
cask "tabby"
cask "raycast"
cask "warp"

tap "homebrew/cask"
tap "hashicorp/tap"
tap "homebrew/cask-fonts"
tap "teamookla/speedtest"

brew "act"
brew "circleci"
brew "coreutils"
brew "exa"
brew "fish"
brew "fisher"
brew "fzf"
brew "gh"
brew "gitmoji"
brew "graphviz"
brew "heroku"
brew "jira-cli"
brew "jp2a"
brew "jq"
brew "neofetch"
brew "neovim"
brew "node-build"
brew "nodenv"
brew "peco"
brew "pyenv"
brew "rbenv"
brew "redis"
brew "ripgrep"
brew "ruby-build"
brew "sl"
brew "starship" # fish prompt https://github.com/starship/starship
brew "tfenv"
brew "tmux"
brew "translate-shell"
brew "vercel-cli"

brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
